services:
  veyo_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: veyo_project
    ports:
      - "3000:3000" 
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
